export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

//users
export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECT = "FETCH_USERS_REJECT";

export const PUT_USER_PENDING = "FETCH_USERS_REJECT";
export const PUT_USER_FULFILLED = "FETCH_USERS_FULFILLED";
export const PUT_USER_REJECT = "FETCH_USERS_PENDING";

//dailySale

export const FETCH_DAILY_SALE_PENDING = "FETCH_DAILY_SALE_PENDING";
export const FETCH_DAILY_SALE_FULFILLED = "FETCH_DAILY_SALE_FULFILLED";
export const FETCH_DAILY_SALE_REJECT = "FETCH_DAILY_SALE_REJECT";
export const CHANGE_DAILY_SALE_BRANCH_DATA = "CHANGE_DAILY_SALE_BRANCH_DATA";
export const PUT_DAILY_SALE_FULFILLED = "PUT_DAILY_SALE_FULFILLED";
export const PUT_DAILY_SALE_REJECT = "PUT_DAILY_SALE_REJECT";

//admin daily sale
export const FETCH_ALL_DAILY_SALE_PENDING = "FETCH_ALL_DAILY_SALE_PENDING";
export const FETCH_ALL_DAILY_SALE_FULFILLED = "FETCH_ALL_DAILY_SALE_FULFILLED";
export const FETCH_ALL_DAILY_SALE_REJECT = "FETCH_ALL_DAILY_SALE_REJECT";


export const FETCH_ALL_DAILY_SALE_RANGE_PENDING = "FETCH_ALL_DAILY_SALE_RANGE_PENDING";
export const FETCH_ALL_DAILY_SALE_RANGE_FULFILLED = "FETCH_ALL_DAILY_SALE_RANGE_FULFILLED";
export const FETCH_ALL_DAILY_SALE_RANGE_REJECT = "FETCH_ALL_DAILY_SALE_RANGE_REJECT";